//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsTextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsTextEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Text Editor .
        /// </summary>
        internal static string Form1_NewFile_Simple_Text_Editor {
            get {
                return ResourceManager.GetString("Form1_NewFile_Simple_Text_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить документ.
        /// </summary>
        internal static string Form1_NewToolStripMenuItem_Click_SaveDoc {
            get {
                return ResourceManager.GetString("Form1_NewToolStripMenuItem_Click_SaveDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В документе есть несохраненные изменения. Нажмите Да чтобы сохранить документ, Нет чтобы отбросить изменения, Отмена для отказа.
        /// </summary>
        internal static string Form1_NewToolStripMenuItem_Click_SaveDocYesNoCancel {
            get {
                return ResourceManager.GetString("Form1_NewToolStripMenuItem_Click_SaveDocYesNoCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Text Editor.
        /// </summary>
        internal static string Form1_SimpleTextEditor {
            get {
                return ResourceManager.GetString("Form1_SimpleTextEditor", resourceCulture);
            }
        }
    }
}
