//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsCapitals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsCapitals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again! :).
        /// </summary>
        internal static string Form1_Loser {
            get {
                return ResourceManager.GetString("Form1_Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tries are left..
        /// </summary>
        internal static string Form1_NumberOfTries {
            get {
                return ResourceManager.GetString("Form1_NumberOfTries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} more capitals are left to win..
        /// </summary>
        internal static string Form1_NumberRightAnswersToWin {
            get {
                return ResourceManager.GetString("Form1_NumberRightAnswersToWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country is {0}. What name is its capital?.
        /// </summary>
        internal static string Form1_Question {
            get {
                return ResourceManager.GetString("Form1_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a winner!.
        /// </summary>
        internal static string Form1_Winner {
            get {
                return ResourceManager.GetString("Form1_Winner", resourceCulture);
            }
        }
    }
}
